### ISSUE TITLE
Basic Sign up View

### ISSUE THREAD

**Issue by 0xLeif** [oneleif/olGO#9]
Sign up Values:

- Email
- Password
- Confirm Password

Buttons:

- Sign up

**Comment by justindbeltran** [comment]
![OneLeif Logo 300](https://user-images.githubusercontent.com/63221090/79283677-e4477200-7efb-11ea-9ad6-72ed3e491676.png)
//above is logo used in assets

import SwiftUI

// change view title to whatever name is actually going to be
struct ContentView: View {
    @State var username = ""
    @State var password = ""
    @State var confirmPassword = ""
    
    var body: some View {
        let cornerRadius: CGFloat = 10
        
        return VStack {
            HStack {
// Image calls on asset logo, may need to rename if asset name changes
                Image("Logo")
                    .resizable()
                    .scaledToFit()
                    .frame(width: 100, height: 100)
                    .cornerRadius(cornerRadius)
                Text("Sign Up for OneLeif!")
                    .font(.title)
                    .fontWeight(.bold)
                    .foregroundColor(.white)
            }
            .padding(.top, 10)
            
            HStack {
                Text("Username:")
                    .padding(.leading, 10)
                    .foregroundColor(.white)
                TextField(" \"John\" ", text: $username)
                    .background(Color.white)
                    .clipShape( Capsule() )
            }
            .padding(.trailing, 10)
            
            HStack {
                Text("Password: ")
                    .padding(.leading, 10)
                    .foregroundColor(.white)
                SecureField(" Check note below", text: $password)
                    .background(Color.white)
                    .clipShape( Capsule() )
            }
            .padding(.trailing, 10)
            
            HStack {
                Text("Confirm:    ")
                    .padding(.leading, 10)
                    .foregroundColor(.white)
                SecureField(" Re-type Here", text: $confirmPassword)
                    .background(Color.white)
                    .clipShape( Capsule() )
            }
            .padding(.trailing, 10)
            .padding(.bottom, 20)
            
                Text("Password must have at least 7 characters   ")
                    .padding(.top, 50)
            
            HStack {
                VStack(alignment: .leading) {
                    Text("At least 1 uppercase")
                    Text("At least 1 number")
                }
                .padding(.trailing, 20)
                VStack(alignment: .leading){
                    Text("At least 1 special")
                    Text("At least 1 lowercase")
                }
            }
            .padding(.bottom, 50)
            
            Button("Submit") {
                self.submit()
            }.disabled(username.isEmpty || passwordProtocol())
            .padding(.horizontal, 50)
            .padding(.vertical)
            .font(.headline)
            .foregroundColor(.white)
            .background(Color.blue)
            .clipShape( Capsule() )
        }
        .frame(
            minWidth: 350,
            idealWidth: 400,
            maxWidth: 450,
            minHeight: 500,
            idealHeight: 600,
            maxHeight: 700,
            alignment: .center)
        .background( Color.init( white: 0.45))
        .cornerRadius(cornerRadius)
        .padding(.horizontal, 10)
        .padding(.bottom, 100)
    }
    private func submit() {
        
///TO DO:  add where the username and password are going to be stored and point to that
        
    }
    private func passwordProtocol() -> Bool {
        var upper = false
        var lower = false
        var numb = false
        var symbol = false
        
        var passwordCheck = false

        for char in password {
            if char.isUppercase {
                upper = true
            } else if char.isLowercase {
                lower = true
            } else if char.isNumber {
                numb = true
            } else if char.isPunctuation || char.isSymbol {
                symbol = true
            }
            if upper && lower && numb && symbol {
                passwordCheck = true
                break
            }
        }
        if passwordCheck && password == confirmPassword {
            return true
        }
        return false
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}

**Comment by justindbeltran** [comment]
<img width="420" alt="Screen Shot 2020-04-13 at 10 27 30 PM" src="https://user-images.githubusercontent.com/63221090/79283805-4b652680-7efc-11ea-8b7c-22845169f17e.png">
//what render looked like

**Comment by 0xLeif** [comment]
[`feature/olgo-9-Sign-Up-View`](https://github.com/oneleif/olGO/tree/feature/olgo-9-Sign-Up-View)
